-- 1. Create the pending_admin_actions table
CREATE TABLE IF NOT EXISTS public.pending_admin_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    action TEXT NOT NULL DEFAULT 'promote',
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'completed', 'failed'
    error_log TEXT,                         -- To record telegram errors if any
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ
);

-- 2. Add description indexes for high-speed lookup by the bot
CREATE INDEX IF NOT EXISTS idx_pending_admin_actions_status ON public.pending_admin_actions(status);
CREATE INDEX IF NOT EXISTS idx_pending_admin_actions_lookup ON public.pending_admin_actions(channel_id, user_id);

-- 3. Enable Row Level Security (RLS) if you want to restrict accesses
ALTER TABLE public.pending_admin_actions ENABLE ROW LEVEL SECURITY;

-- 4. Create Security Policies
-- Allow Service Role Key or Authenticated Users (Admins on the web panel) to insert actions
CREATE POLICY "Allow service role or admin inserts" ON public.pending_admin_actions
    FOR INSERT
    WITH CHECK (true);

-- Allow admins or service role to select/update actions
CREATE POLICY "Allow service role or admin selects" ON public.pending_admin_actions
    FOR SELECT
    USING (true);

CREATE POLICY "Allow service role or admin updates" ON public.pending_admin_actions
    FOR UPDATE
    USING (true);
